# Imagen base de Nginx
FROM nginx:alpine

# Crear archivo HTML simple
RUN echo '<!DOCTYPE html><html><head><title>Curso Leonisa</title></head><body><h1>Bienvenido al Curso Leonisa en el puerto 9090</h1></body></html>' \
    > /usr/share/nginx/html/index.html

# Exponer el puerto 9090
EXPOSE 9090

# Configuración personalizada de Nginx para escuchar en el puerto 9090
RUN rm /etc/nginx/conf.d/default.conf && \
    echo 'server { \
        listen 9090; \
        server_name localhost; \
        location / { \
            root   /usr/share/nginx/html; \
            index  index.html; \
        } \
    }' > /etc/nginx/conf.d/default.conf

# Comando por defecto de Nginx
CMD ["nginx", "-g", "daemon off;"]